export const binance_api = "https://api.binance.com/wapi/v3/systemStatus.html";
export const ticker_api =
  "https://api.coinmarketcap.com/v1/ticker/?convert=usd&limit=3";
export const login_uri = "/login";
export const data_uri = "/monitoring/data";

export const actions = {
  REQUEST_MONITORING: "REQUEST_MONITORING",
  REQUEST_MONITORING_SUCCESS: "REQUEST_MONITORING_SUCCESS",
  REQUEST_MONITORING_FAILURE: "REQUEST_MONITORING_FAILURE",
  REQUEST_LOGIN_BEGIN: "REQUEST_LOGIN_BEGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  RESET_LOGIN: "RESET_LOGIN",
  REQUEST_DATA_NOT_RECEIVED: "REQUEST_DATA_NOT_RECEIVED",
  BINANCE_API_ONLINE: "BINANCE_API_ONLINE",
  BINANCE_API_OFFLINE: "BINANCE_API_OFFLINE",
  UPDATE_TICKER_DATA: "UPDATE_TICKER_DATA",
  USER_UPDATED: "USER_UPDATED",
  RECEIVED_CONFIG_SUCCCESSFUL: "RECEIVED_CONFIG_SUCCCESSFUL",
  CONFIGS_PROCESSED: "CONFIGS_PROCESSED"
};
